### ISSUE TITLE
Include license file in source distribution

### ISSUE THREAD

**Issue by synapticarbors** [GRV96/path_checker#12]
It would be helpful to include the license file in the source distribution either via the `setup.cfg` file or `MANIFEST.in`.

**Comment by GRV96** [comment]
@synapticarbors I prefer to include the license file in setup.py with argument license_files. Is that acceptable?
Reference: https://setuptools.pypa.io/en/stable/references/keywords.html

**Comment by synapticarbors** [comment]
If that works, that's fine. I've always found the documentation a little lacking in terms of being explicit about what the keyword does. I've been meaning to test it, but I know that `MANIFEST.in` definitely works:

https://packaging.python.org/guides/using-manifest-in/

as does `license_files` in `setup.cfg` as also documented in the link.
